apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.name }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.db.user | quote }}
  SERVER_PORT: {{ .Values.service.port | quote }}
  {{- range $key, $value := .Values.config.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
